services:
  qgis:
    build:
      context: platypus
      dockerfile: Dockerfile
      args:
        - MSSQL_SA_PASSWORD
    restart: unless-stopped
    
  db:
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD:?Please set a secure password for MSSQL}"
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    healthcheck:
        test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${MSSQL_SA_PASSWORD} -Q 'SELECT 1' || exit 1"]
        interval: 10s
        retries: 10
        start_period: 10s
        timeout: 3s
    ports:
      - "1433:1433"